# Generated by Django 5.2.4 on 2025-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_at_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_parcels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
